package jp.fedom.challange.google.codejam2016.r1b.q1;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import jp.fedom.challange.google.codejam2016.r1b.q1.Main.Question;
import jp.fedom.challange.google.common.Utils;

import org.junit.Test;
import static org.hamcrest.CoreMatchers.*;

public class MainTest {

	@Test
	public void test_solve_sample1() {
		Question q = new Question();
		q.s = "OZONETOWER";
		assertEquals("Case #1: 012", Main.solve(q, 1));
	}
	@Test
	public void test_solve_sample2() {
		Question q = new Question();
		q.s = "WEIGHFOXTOURIST";
		assertEquals("Case #2: 2468", Main.solve(q, 2));
	}

	@Test
	public void test_solve_sample3() {
		Question q = new Question();
		q.s = "EXFUVFRSIEENVIOS";
		assertEquals("Case #2: 4567", Main.solve(q, 2));
	}
	
	@Test
	public void test_solve_sample4() {
		Question q = new Question();
		q.s = "IVEFVTNEEUOIENIGTEUNTEHONIRZEEWENRUEZEFNNZITNTRXREEEEEHRRHTUVHEIROZVIISGEXFEETNOIGGFNVRFSTEUTNEEGEESEOIIRETUOVIVERFOSRSISOEVNNEFESGGFEIFNITENWNTOEFTTOFZEEEENNNENRNOEENRSREEHHNESENUOFNTEUFRTWIEITEFETENNOVSWEISEEREENEIUOVOIVXENHRWHOTTEFVEEITSGHEOFFTIIRTONRHSEREOTZXIEERISEENOUEERERNEVIENUOOZNXNEVOIIGUESZIRTHETNIEFEEEHRHNEOSEOESETONSRTOTEEVRSNWIREENTZEIIHNVIEVEUTHINETIEIRFTNGNNXTURHOTEXVEOUSITEVISNIUHNNOFTENOOOEESVSRFITFIUVNOGEHFNHOERHNNFWGTOVIENORINNENNEEOOIWETZFEEETESTIRNXSTUITEVFEZNFIEOETEEOONERZNVERNRNEUXGVXNUUOIEOOITTRVSOEERTHNEFEZEIEHVHEIOVOIRETERSEIOEIONENHVNZENRTTNENNOTRINEVORSTISFISXSTEWNOEEXNHFNFENNENVROIENRVOINNOHXXEFEENWSEETEEEOEUNOUNEFFENIVEREXETHURNIXHOWOFTEOZEENEGTHNTUOHXEEVRSRESHHRETNSEETWHIVRHOVOROOSEFVURNOTRRRINETOIIGFEEEHTEEWOEXOSEUOEWOIWHGITTIENGIGEZEEERXZOUEVUEREHIWOHOXHFNFNFFTHIRRINXOHRGSOOUVISIHENNEFETETEEHEVXFTTGNTNNNEIESEFREUIHRREEGFRHTHRONZEHTEGTZZIOFHIVNSIOIEESISOZERZEOHIVGEESSSNRVEERUEESIEEUOIIHINERVENOIVETNRRZOEEFTUNERNISONOERHEIOEESSFIXRFWNZENIGISITWIWTSEGOWTENNOEOSOEOEGINEEEUEHVORNNROENIVRFOEERHVVTOEFEENNEENTREIZEFUWOTRORNEEIHWERENIEONNIEOHREENIHHOESEUIEEIIEGSTEIEFRXOSEFTHOUNIFEENNXGRUEUEHWVVOOISENERENHSTIEOTTIESNORSSVWXENGFWRNOIHREEERENWNENNSVNNRTTTROXVOONOUEEINTOFTTNNFIUOEVZHREIEEIVOUNENESWNOEFESOWOIVNNREOEOONVNITRNXINEIHENHNVIHOVSVEIGRFEFIXNTIIIREENGNENERWITZEEOEVIRIFNNEEOOFWIEEEEENIEVOHIWEHISTHTETRFEFNEIEGENETNVOFENNETIISEIEFSXIGWNTEENSVIIZWIEEEHWNFUNHTXSNGTIOGISESGRUTTHEVORUEIIENEEESEOEREHIOOSEORHHOINEZRIITSZEFSRRETNNINOREEHNVGRSRRNEEXXG";
//		assertEquals("Case #2: 4567", Main.solve(q, 2));
	}

	
	@Test
	public void show(){
		String[] digits = new String[]{"ZERO", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE"};
		digits = new String[]{"ONE",    "NINE"};
//
//		c = extract(q, ans, c, wcount, "TWO", 2);
//		c = extract(q, ans, c, xcount, "SIX", 6);
//		c = extract(q, ans, c, zcount, "ZERO", 0);
//		c = extract(q, ans, c, ucount, "FOUR", 4);
//		c = extract(q, ans, c, gcount, "EIGHT", 8);
		
		Map<String, Integer> c = new HashMap<>();
		for(String s : digits){
			for(char ch : s.toCharArray()){
				s = String.valueOf(ch);
				if(!c.containsKey(String.valueOf(s))){
					c.put(s, 0);
				}
				c.put(s, c.get(s) + 1);
			}
		}
//		
		for(Map.Entry<String, Integer> e: c.entrySet()){
			System.out.println(e.getKey() + " : " + e.getValue());
		}
	}
}
	

